#!/bin/bash
set -ex

# Create the 'counter' system user if it doesn't exist
if ! id "counter" &>/dev/null
then
	adduser --system --no-create-home --home /nonexistent --disabled-login --group counter
fi

# Reload systemd
systemctl daemon-reexec
systemctl daemon-reload

# Enable the counter service to start on boot
systemctl enable counter.service

# Start the counter service immediately
systemctl start counter.service
