name: Counter Self-Hosted VM Deployment
run-name: ${{ github.actor }} is testing out Counter Self-Hosted VM Deployment 🚀
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: [self-hosted, linux, CPSC334]
    timeout-minutes: 2
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y g++ make

      - name: Build project
        run: make -j$(nproc) build

  test:
    needs: build
    runs-on: [self-hosted, linux, CPSC334]
    timeout-minutes: 2
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y g++ cmake make
      
      - name: Install Google Test
        run: |
          git clone https://github.com/google/googletest.git
          cd googletest
          mkdir build && cd build
          cmake ..
          make -j$(nproc)
          sudo make -j$(nproc) install
          cd ..

      - name: Run tests
        run: make -j$(nproc) test

  build-deb:
    needs: test
    runs-on: [self-hosted, linux, CPSC334]
    timeout-minutes: 5
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y g++ cmake make binutils dpkg

      - name: Install Google Test
        run: |
          git clone https://github.com/google/googletest.git
          cd googletest
          mkdir build && cd build
          cmake ..
          make -j$(nproc)
          sudo make -j$(nproc) install
          cd ..

      - name: Build deb package
        run: make -j$(nproc) build-deb

      - name: Archive deb package
        uses: actions/upload-artifact@v4
        with:
          name: counter-deb-package
          path: counter-v2.0.0.deb

  lint-deb:
    needs: build-deb
    runs-on: [self-hosted, linux, CPSC334]
    timeout-minutes: 2
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y lintian make

      - name: Download deb package artifact
        uses: actions/download-artifact@v4
        with:
          name: counter-deb-package

      - name: Lint counter deb package
        run: make -j$(nproc) lint-deb

  deploy:
    needs: lint-deb
    runs-on: [self-hosted, linux, CPSC334]
    timeout-minutes: 2
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Download deb package artifact
        uses: actions/download-artifact@v4
        with:
          name: counter-deb-package
          path: ./downloads
        
      - name: Copy deb package to counter
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.COUNTER_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "downloads/counter-v2.0.0.deb"
          target: "/home/${{ secrets.USERNAME }}"

      - name: Build package on counter vm
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.COUNTER_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: dpkg -i counter-v2.0.0.deb
